apiVersion: v1
kind: Pod
metadata:
  name: hitachi-nfs-pod2
spec:
  
  containers:
  - name: nginx
    image: nginx
   
    volumeMounts:
    - name: efs-vol
      mountPath: /logs
    - name: cache
      mountPath: /var/cache/nginx
  volumes:
  - name: efs-vol
    persistentVolumeClaim:
      claimName: efs-pvc2 
  - name: cache
    emptyDir: {}