apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-shared-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ebs-sc-rwx
  resources:
    requests:
      storage: 100Gi
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc-rwx
provisioner: ebs.csi.aws.com
allowVolumeExpansion: true
parameters:
  type: gp3
  iops: "3000"
  throughput: "125"
  fstype: ext4
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: Pod
metadata:
  name: vm-1
  namespace: default
spec:
  containers:
  - name: app-1
    image: busybox
    volumeMounts:
    - name: shared-storage
      mountPath: /data
  volumes:
  - name: shared-storage
    persistentVolumeClaim:
      claimName: ebs-shared-pvc
---
apiVersion: v1
kind: Pod
metadata:
  name: vm-2
  namespace: default
spec:
  containers:
  - name: app-2
    image: busybox
    volumeMounts:
    - name: shared-storage
      mountPath: /data
  volumes:
  - name: shared-storage
    persistentVolumeClaim:
      claimName: ebs-shared-pvc