apiVersion: apps/v1
kind: Deployment
metadata:
  name: shared1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: v1
          mountPath: /hitachi-logs
      volumes:
      - name: v1
        persistentVolumeClaim:
          claimName: pvc2