apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc1
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-034ea6fb9afa12130
  directoryPerms: "777"
  gidRangeStart: "400"
  gidRangeEnd: "2000"
  basePath: "/"
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true