apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-07bbb173e9ff0520f
  directoryPerms: "777"
  gidRangeStart: "400"
  gidRangeEnd: "2000"
  basePath: "/"
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true